fix: revision compare bug (#0)
Signed-off-by: tkrop <tronje.krop@zalando.de>

diff --git a/Makefile.base b/Makefile.base
--- a/Makefile.base
+++ b/Makefile.base
@@ -401,19 +401,18 @@ fix-update:
 
 #@ <version|major|minor|patch[+-]?> # update version and prepare release of the software.
 bump:
-	@if [ -z "$(RUNARGS)" ]; then \
-	  echo "error: missing new version"; exit 1; \
-	elif [[ "$(RUNARGS)" =~ ^(major|minor|patch|[.+-]*)[+-]?$$ ]]; then \
-	  VERSION="$$(awk -v arg=$(RUNARGS) '{ \
+	@if [ -z "$(RUNARGS)" ]; then ARGS="patch"; else ARGS="$(RUNARGS)"; fi; \
+	if [[ "$${ARGS}" =~ ^(major|minor|patch|[.+-]*)[+-]?$$ ]]; then \
+	  VERSION="$$(awk -v arg=$${ARGS} '{ \
 	    op["major"] = 1; op["minor"] = 2; op["patch"] = 3; \
 		if ((pos = op[substr(arg,1,5)]) == 0) { pos = length(arg) }; \
 	    patsplit($$0, v, "[0-9]*", seps); len = length(seps); \
 	    if (arg !~ "-$$") {v[pos]++ } else { v[pos]-- }; \
 	    for (i = 1; i < len; i++) { printf("%d%s", v[i], seps[i]) } \
 	  }' VERSION)"; \
-	elif ! [[ "$(RUNARGS)" =~ ^[0-9]+(\.[0-9]+){0,2}(-.*)?$$ ]]; then \
-	  echo "error: invalid new version [$(RUNARGS)]"; exit 1; \
-	else VERSION="$(RUNARGS)"; fi; echo $${VERSION} >VERSION; \
+	elif ! [[ "$${ARGS}" =~ ^[0-9]+(\.[0-9]+){0,2}(-.*)?$$ ]]; then \
+	  echo "error: invalid new version [$${ARGS}]"; exit 1; \
+	else VERSION="$${ARGS}"; fi; echo $${VERSION} >VERSION; \
 	echo "Bumped version to $${VERSION} for auto release!"; \
 
 
