feat: improve go.mod and go.sum dependencies (#140)
Signed-off-by: Tronje Krop <tronje.krop@jactors.de>

diff --git a/Makefile.ext b/Makefile.ext
--- a/Makefile.ext
+++ b/Makefile.ext
@@ -18,7 +18,7 @@ commit:: sync-check
 sync-check::
 	@for FILE in $$(find config -type f ! -name "Makefile.vars" ! -name "Makefile"); do \
 	  if [ -f "$${FILE#*/}" ] && [ -n "$$(diff "$${FILE}" "$${FILE#*/}")" ]; then \
-	    echo "error: $${FILE} (not synchronized)" > "/dev/stderr"; exit -1; \
+	    echo "error: $${FILE} (not synchronized)" >&2; exit -1; \
 	  fi; \
 	done;
 
